name: Commento su commit automatico

on:
    push:
      branches:
        - main
  
jobs:
    comment-on-commit:
        runs-on: ubuntu-latest
        steps:

            - name: checkout
              uses: actions/checkout@v3

            - name: Avvia git
              run: |
                git fetch --prune --unshallow

            - name: Verifica differenza tra commit
              id: diff
              run: |
                git diff --unified=5 HEAD~1 HEAD > diff.txt  # Estrae le differenze tra il commit attuale e quello precedente
                cat diff.txt  
                echo "::set-output name=diff::$(cat diff.txt)"
            
            - name: Create commit comment
              uses: actions/github-script@v6
              with:
                  script: |
                      const body = "Test comment for commit.";
                      try {
                        await github.rest.issues.createComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: 1, 
                          body: body
                        });
                      } catch (error) {
                        core.setFailed(`Failed to create comment: ${error.message}`);
                      }
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}





                    