name: Commento su commit automatico

on:
    push:
      branches:
        - main

jobs:
    comment-on-commit:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout codice
              uses: actions/checkout@v3

            - name: Avvia git
              run: |
                git fetch --prune --unshallow

            - name: Verifica differenza tra commit
              id: diff
              run: |
                git diff --unified=5 HEAD~1 HEAD > diff.txt
                cat diff.txt
                echo "{\"diff\": \"$(cat diff.txt)\"}" > diff.json

            - name: Crea commento sul commit
              uses: actions/github-script@v6
              with:
                script: |
                  const commitMessage = `${{ github.event.head_commit.message }}`;  
                  const sha = `${{ github.sha }}`; 
                  const diff = require('./diff.json').diff; 
                  const body = `### Dettagli del commit:\n\n**Messaggio del commit**: ${commitMessage}\n\n**Differenze principali**:\n\`\`\`diff\n${diff}\n\`\`\``;
                  try {
                    await github.rest.repos.createCommitComment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      commit_sha: sha,  
                      body: body  
                    });
                  } catch (error) {
                    core.setFailed(`Failed to create commit comment: ${error.message}`);
                  }
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




                    