name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'App.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Usa la versione corretta per fare il checkout del repository

     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configura Docker Buildx per il build

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.USERNAME }}/flask-app:latest .    
  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Esegui il login su Docker Hub
        with:
          username: ${{ secrets.USERNAME }}  
          password: ${{ secrets.KEY }}
      - name: Push Docker image
        run: |
          docker push ${{ secrets.USERNAME }}/flask-app:latest  

